config/routes.rb
Rails.application.routes.draw do
  root "users#new"

  get "tasks/index" => "tasks#index"
  post "tasks/create" => "tasks#create"
  patch "tasks/update" => "tasks#update"
  delete "tasks/destroy" => "tasks#destroy"

  get "/users/signup", to: "users#new", as: "signup"
  get "/users/login", to: "users#login", as: "login"
  post "/users" => "users#create"
  get "/users/:id", to: "users#show", as: "user"
  get "/users/edit/:id", to: "users#edit", as: "edit"
  post "/users/validate", to: "users#validate", as: "validate"
  patch "/users/:id", to: "users#update"
  delete "/users/:id", to: "users#destroy", as: "destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    validates :user_id, presence: true
    validates :task_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :tasks, dependent: :destroy
    validates :user_name, presence: true
    validates :user_mail, presence: true, uniqueness: true
    validates :password_digest, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index
    end

    def create
    end

    def update
    end

    def destroy
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
    end

    def show
        @user = User.find(params[:id])
    end

    def create
        @user = User.new(user_name: params[:user][:name], user_mail: params[:user][:mail], password: params[:user][:password_digest],  password_confirmation: params[:user][:password_digest])
        if @user.save
            redirect_to "/users/#{@user.id}"
        else
            render :user_error, status: :unprocessable_entity
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_name: params[:user][:user_name], user_mail: params[:user][:user_mail], password: params[:user][:password_digest], password_confirmation: params[:user][:password_digest])
            redirect_to "/users/#{@user.id}"
        else
            render :user_error, status: :unprocessable_entity
        end
    end

    def new
        @user = User.new  # これ消すな！　form_with に mode: @user 指定するために必要！
    end

    def login
    end

    def validate
        # email から DB のオブジェクト取得
        # password のハッシュ化と，オブジェクトのパスワード比較して認証
        @user = User.find_by(user_mail: params[:user_mail])
        if @user && @user.authenticate(params[:password])
            redirect_to user_path(@user)
        else
            redirect_to login_path
        end
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to login_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Railsgirls" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1> Tasks#index </h1>
<p> This is a Test String </p>
<p> クライアント用のフォーム実装（テスト）</p>
<%= form_with do |form|  %>
    <%= form.label :task %>
    <%= form.text_field  %>
<% end %>

app/views/users/edit.html.erb
<p> test user </p>
<p> <%= @user.user_name %> </p>
<p> <%= @user.user_mail %> のページ</p>

<%= form_with(model: @user,method: "patch") do |form|  %>
    <%= form.label  :user_name %>
    <%= form.text_field :user_name %>
    
    <%= form.label :user_mail %>
    <%= form.text_field :user_mail %>

    <%= form.label :password_digest %>
    <%= form.text_field :password_digest %>
    
    <%= form.submit "ユーザーデータ更新" %>
<% end %>

app/views/users/login.html.erb
<%= form_with(url: validate_path, method: "post") do |form|  %>
    <%= form.label  :user_name %>
    <%= form.text_field :user_name %>
    
    <%= form.label :user_mail %>
    <%= form.text_field :user_mail %>

    <%= form.label :password %>
    <%= form.password_field :password %>
    
    <%= form.submit "login" %>
<% end %>

app/views/users/new.html.erb
<h1> Users New </h1>
<p> This is a Test String </p>
<p> クライアント登録用のフォーム実装（テスト）</p>
<%= form_with(model: @user) do |form|  %>
    <%= form.label  :user_name %>
    <%= form.text_field :name %>
    
    <%= form.label :user_mail %>
    <%= form.text_field :mail %>

    <%= form.label :password_digest %>
    <%= form.password_field :password_digest %>
    
    <%= form.submit "送信" %>
<% end %>

app/views/users/show.html.erb
<p> test user </p>
<p> <%= @user.user_name %> </p>
<p> <%= @user.user_mail %> </p>
<li><%= button_to "Destroy" , user_path(@user), method: :delete %>

app/views/users/user_error.html.erb
<h1> Error </h1>
<p> This is a Test String </p>
<p> クライアント登録用のフォームError（テスト）</p>
<%= form_with(model: @user) do |form|  %>
    <%= form.label  :user_name %>
    <%= form.text_field :user_name %>
    
    <%= form.label :user_mail %>
    <%= form.text_field :user_mail %>

    <%= form.label :password_digest %>
    <%= form.text_field :password_digest %>
    
    <%= form.submit "再送信" %>
<% end %>